/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/simulate/hiring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run hiring stress test
         * @description Stress-tests downside scenarios to assess hiring risk.
         */
        get: operations["simulate_hiring_api_v1_simulate_hiring_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HiringSimResponse */
        HiringSimResponse: {
            /**
             * Status
             * @description safe | risky | dangerous
             */
            status?: string | null;
            /** Time To Layoff Zone Months */
            time_to_layoff_zone_months?: number | null;
            /** Time To Payroll Breach Months */
            time_to_payroll_breach_months?: number | null;
            /** Horizon Months */
            horizon_months?: number | null;
            earliest_event?: components["schemas"]["RiskEvent"] | null;
            /** Breakpoints */
            breakpoints?: string[] | null;
            /** What Breaks First */
            what_breaks_first?: string | null;
            /** Suggested Action */
            suggested_action?: string | null;
            /** Assumptions Used */
            assumptions_used?: {
                [key: string]: unknown;
            } | null;
        };
        /** RiskEvent */
        RiskEvent: {
            /** Type */
            type: string;
            /** Month */
            month: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    simulate_hiring_api_v1_simulate_hiring_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HiringSimResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
