/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/simulate/hiring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run hiring stress test
         * @description Stress-tests downside scenarios to assess hiring risk for SMEs.
         */
        post: operations["simulate_hiring_api_v1_simulate_hiring_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HiringSimRequest
         * @description API request schema for hiring simulation.
         *
         *     All fields optional - if not provided, engine applies domain defaults.
         *     This is a thin HTTP boundary; business logic/defaults live in engine layer.
         */
        HiringSimRequest: {
            /**
             * Cash Balance Eur
             * @description Starting cash balance (EUR)
             */
            cash_balance_eur?: number | null;
            /**
             * Current Monthly Payroll Eur
             * @description Current monthly payroll, fully loaded (EUR)
             */
            current_monthly_payroll_eur?: number | null;
            /**
             * Employer Cost Multiplier
             * @description Gross to fully-loaded cost multiplier
             */
            employer_cost_multiplier?: number | null;
            /**
             * Fixed Costs Monthly Eur
             * @description Monthly fixed non-payroll costs (EUR)
             */
            fixed_costs_monthly_eur?: number | null;
            /**
             * Baseline Monthly Revenue Eur
             * @description Current monthly revenue (EUR)
             */
            baseline_monthly_revenue_eur?: number | null;
            /**
             * Utilization Pct
             * @description Current utilization percentage (0-100)
             */
            utilization_pct?: number | null;
            /**
             * Client Concentration Pct
             * @description Largest client as % of revenue (0-100)
             */
            client_concentration_pct?: number | null;
            /**
             * Dso Days
             * @description Days Sales Outstanding (payment collection time)
             */
            dso_days?: number | null;
            /**
             * New Hire Gross Annual Eur
             * @description Gross annual salary for new hire (EUR)
             */
            new_hire_gross_annual_eur?: number | null;
            /**
             * New Hire Revenue Multiplier
             * @description Expected revenue as multiple of salary
             */
            new_hire_revenue_multiplier?: number | null;
            /**
             * Country Code
             * @description Country code for defaults (DE, FR, etc.)
             * @default DE
             */
            country_code: string | null;
            /**
             * Scenario Type
             * @description Scenario to run: base_case, mild_downside, realistic_downside
             * @default realistic_downside
             */
            scenario_type: string | null;
        };
        /** HiringSimResponse */
        HiringSimResponse: {
            /**
             * Status
             * @description safe | risky | dangerous
             */
            status?: string | null;
            /** Time To Layoff Zone Months */
            time_to_layoff_zone_months?: number | null;
            /** Time To Payroll Breach Months */
            time_to_payroll_breach_months?: number | null;
            /** Horizon Months */
            horizon_months?: number | null;
            earliest_event?: components["schemas"]["RiskEvent"] | null;
            /** Breakpoints */
            breakpoints?: string[] | null;
            /** What Breaks First */
            what_breaks_first?: string | null;
            /** Suggested Action */
            suggested_action?: string | null;
            /** Assumptions Used */
            assumptions_used?: {
                [key: string]: unknown;
            } | null;
        };
        /** RiskEvent */
        RiskEvent: {
            /** Type */
            type: string;
            /** Month */
            month: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    simulate_hiring_api_v1_simulate_hiring_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HiringSimRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HiringSimResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
